Hour 1 — NumPy Foundations

In [1]:
import numpy as np
import pandas as pd

In [2]:
sales = np.array([600, 1200, 300, 900, 500, 700, 400, 1000])

print(sales)
print(type(sales))

[ 600 1200  300  900  500  700  400 1000]
<class 'numpy.ndarray'>


In [3]:
quantities = np.array([2,1,3,1,4,2])

print(quantities)
print(type(quantities))

[2 1 3 1 4 2]
<class 'numpy.ndarray'>


In [4]:
double_quantities = quantities * 2

print(double_quantities)

[4 2 6 2 8 4]


Element-by-Element Math

In [5]:
prices = np.array([300, 1200, 100, 300, 250, 100])

In [6]:
total_sales = prices * quantities

print(total_sales)

[ 600 1200  300  300 1000  200]


Shape and Size

In [7]:
total_sales.shape

(6,)

In [8]:
total_sales.size

6

Indexing

In [9]:
print(total_sales)

[ 600 1200  300  300 1000  200]


In [10]:
print(total_sales[0])
print(total_sales[2])
print(total_sales[-1])

600
300
200


Slicing

[start : stop]  
include   exclude

In [11]:
print(total_sales[1:4])
print(total_sales[:3])
print(total_sales[3:])

[1200  300  300]
[ 600 1200  300]
[ 300 1000  200]


Boolean Filtering

In [12]:
print(total_sales)

[ 600 1200  300  300 1000  200]


In [13]:
#mask
total_sales > 500

array([ True,  True, False, False,  True, False])

In [14]:
total_sales[total_sales > 500]

array([ 600, 1200, 1000])

Return only sales that are greater than or equal to $600.

In [15]:
high_sales = total_sales[total_sales >= 600]

In [16]:
print(high_sales)

[ 600 1200 1000]


Let's combine multiple NumPy concepts.

In [17]:
total_sales = quantities * prices
print(total_sales)

[ 600 1200  300  300 1000  200]


In [18]:
filtered_sales = total_sales[(total_sales >= 500) & (quantities >= 2)]
print(filtered_sales)

[ 600 1000]


Hour 2 — NumPy Statistics

In [19]:
total_revenue = np.sum(total_sales)
average_sale = np.mean(total_sales)
median_sale = np.median(total_sales)
minimum_sale = np.min(total_sales)
maximum_sale = np.max(total_sales)

In [20]:
print(total_revenue)
print(average_sale)
print(median_sale)
print(minimum_sale)
print(maximum_sale)

3600
600.0
450.0
200
1200


Standard Deviation

In [21]:
sales_std = np.std(total_sales)
print(sales_std)

378.59388972001824


Variance

In [ ]:
sales_variance = np.var(total_sales)
print(sales_variance)

143333.33333333334


In [24]:
sales_std ** 2

np.float64(143333.33333333334)

Percentiles

In [25]:
q1 = np.percentile(total_sales, 25)
median = np.percentile(total_sales, 50)
q3 = np.percentile(total_sales, 75)

In [26]:
print(q1)
print(median)
print(q3)

300.0
450.0
900.0


Interquartile Range (IQR).

In [27]:
iqr = q3 - q1

In [28]:
print(iqr)

600.0


Outlier Boundaries

In [31]:
lower_bound = q1 - (1.5 * iqr)
upper_bound = q3 + (1.5 * iqr)

In [32]:
print(lower_bound)
print(upper_bound)

-600.0
1800.0


Find Outliers

In [33]:
outliers = total_sales[
    (total_sales < lower_bound) |
    (total_sales > upper_bound)
]
print(outliers)

[]


Hour 3 — Exploratory Data Analysis with Pandas

In [34]:
sales_df = pd.DataFrame({
    "order_id": range(1001, 1013),
    "product": [
        "Laptop", "Monitor", "Keyboard", "Laptop",
        "Monitor", "Keyboard", "Laptop", "Monitor",
        "Keyboard", "Laptop", "Monitor", "Keyboard"
    ],
    "quantity": [1, 2, 3, 1, 2, 5, 1, 3, 2, 1, 2, 4],
    "total_sales": [
        1200, 600, 300, 1200,
        600, 500, 1200, 900,
        200, 1200, 600, 400
    ]
})

display(sales_df)

,order_id,product,quantity,total_sales
0,1001,Laptop,1,1200
1,1002,Monitor,2,600
2,1003,Keyboard,3,300
3,1004,Laptop,1,1200
4,1005,Monitor,2,600
5,1006,Keyboard,5,500
6,1007,Laptop,1,1200
7,1008,Monitor,3,900
8,1009,Keyboard,2,200
9,1010,Laptop,1,1200


describe()

In [35]:
sales_df.describe()

,order_id,quantity,total_sales
count,12.000000,12.000000,12.000000
mean,1006.500000,2.250000,741.666667
std,3.605551,1.288057,380.091695
min,1001.000000,1.000000,200.000000
25%,1003.750000,1.000000,475.000000
50%,1006.500000,2.000000,600.000000
75%,1009.250000,3.000000,1200.000000
max,1012.000000,5.000000,1200.000000


Product-Level EDA

How do sales differ by product?

In [36]:
product_summary = sales_df.groupby("product").agg(
    order_count=("order_id", "count"),
    average_sales=("total_sales", "mean"),
    median_sales=("total_sales", "median"),
    minimum_sales=("total_sales", "min"),
    maximum_sales=("total_sales", "max")
).reset_index()

In [37]:
print(product_summary)

    product  order_count  average_sales  median_sales  minimum_sales  \
0  Keyboard            4          350.0         350.0            200   
1    Laptop            4         1200.0        1200.0           1200   
2   Monitor            4          675.0         600.0            600   

   maximum_sales  
0            500  
1           1200  
2            900  


Calculate Range

In [38]:
product_summary["sales_range"] = (
    product_summary["maximum_sales"] - product_summary["minimum_sales"]
)

Standard Deviation by Product

In [39]:
product_variability = sales_df.groupby("product").agg(
    average_sales=("total_sales", "mean"),
    sales_std=("total_sales", "std")
).reset_index()

display(product_variability)

,product,average_sales,sales_std
0,Keyboard,350.0,129.099445
1,Laptop,1200.0,0.000000
2,Monitor,675.0,150.000000


Find Unusually Large Sales

In [42]:
q1 = sales_df["total_sales"].quantile(0.25)
q3 = sales_df["total_sales"].quantile(0.75)

iqr = q3 - q1

In [43]:
lower_bound = q1 - (1.5 * iqr)
upper_bound = q3 + (1.5 * iqr)

In [44]:
potential_outliers = sales_df[
    (sales_df["total_sales"] < lower_bound) |
    (sales_df["total_sales"] > upper_bound)
]

Hour 4 — Apply EDA to Our Project

In [45]:
project_sales = pd.read_csv("../data/sales_analysis_clean.csv")

display(project_sales)

,order_id,customer_id,product_id,quantity,customer_name,state,product_name,price,total_sales
0,1001,1,10,2,Alex,CA,Laptop,1200,2400
1,1003,2,10,1,Maria,CA,Laptop,1200,1200
2,1005,3,11,2,James,TX,Monitor,300,600
3,1002,1,11,1,Alex,CA,Monitor,300,300
4,1004,3,12,3,James,TX,Keyboard,100,300


How is sales performance different across products?

In [46]:
project_product_summary = project_sales.groupby("product_name").agg(
    order_count=("order_id", "count"),
    total_revenue=("total_sales", "sum"),
    average_order_sales=("total_sales", "mean"),
    total_quantity=("quantity", "sum")
).reset_index()

Rank Products

Which products generate the most total revenue?

In [48]:
project_product_summary = project_product_summary.sort_values(
    "total_revenue",
    ascending=False
)

display(project_product_summary)

,product_name,order_count,total_revenue,average_order_sales,total_quantity
1,Laptop,2,3600,1800.0,3
2,Monitor,2,900,450.0,3
0,Keyboard,1,300,300.0,3


Add Revenue Share

What percentage of total company revenue comes from each product?

In [49]:
total_revenue = project_product_summary["total_revenue"].sum()

In [50]:
print(total_revenue)

4800


In [ ]:
project_product_summary["revenue_share"] = (
    project_product_summary["total_revenue"] / total_revenue
)

Outlier Check

Calculate Q1 and Q3

In [54]:
q1 = project_sales["total_sales"].quantile(0.25)
q3 = project_sales["total_sales"].quantile(0.75)

calculate the IQR and the lower/upper outlier boundaries

In [56]:
iqr = q3 - q1
lower_bound = q1 - (1.5 * iqr)
upper_bound = q3 + (1.5 * iqr)

use those boundaries to find the potential outliers

In [57]:
project_outliers = project_sales[
    (project_sales["total_sales"] < lower_bound) |
    (project_sales["total_sales"] > upper_bound)
]

display(project_outliers)

,order_id,customer_id,product_id,quantity,customer_name,state,product_name,price,total_sales


Save Our Day 5 Output

In [58]:
project_product_summary.to_csv(
    "../data/day_05_product_eda_summary.csv",
    index=False
)

In [59]:
check = pd.read_csv("../data/day_05_product_eda_summary.csv")
display(check)

,product_name,order_count,total_revenue,average_order_sales,total_quantity,revenue_share
0,Laptop,2,3600,1800.0,3,0.7500
1,Monitor,2,900,450.0,3,0.1875
2,Keyboard,1,300,300.0,3,0.0625
